Repository MarquezProject/marquez-web, pull requests merged in 2020-11, with the labels that each got.

#126 Removing extra configuration that is not used anymore.
  src/config/__mocks__/tag-to-badge.tsx
Labels: cleanup

#127 Update preview.png for release 0.7.0
  docs/images/preview.png
  src/components/App.tsx
Labels: review

#131 Fixing the tests and CI build
  src/__tests__/components/DatasetDetailPage.test.tsx
  src/__tests__/components/DatasetPreviewCard.test.tsx
  src/__tests__/components/Filters.test.tsx
  src/__tests__/components/Toast.test.tsx
  src/__tests__/components/__snapshots__/DatasetDetailPage.test.tsx.snap
  src/__tests__/components/__snapshots__/DatasetPreviewCard.test.tsx.snap
  src/__tests__/components/__snapshots__/Filters.test.tsx.snap
  src/components/Toast.tsx
Labels: bug, cleanup

#130 Remove Network Graph
  src/__tests__/components/NetworkGraph.test.tsx
  src/__tests__/components/__snapshots__/NetworkGraph.test.tsx.snap
  src/components/NetworkGraph.tsx
Labels: cleanup
